name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 */6 * * *" # See https://crontab.guru/#0 */6 * * *

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "ghulam.yanuar01@gmail.com"
          git config --local user.name "ghulam46"
          git add -A
          
          arr[0]="chore(bot): 😂 plant tree 🌳"
          arr[1]="chore(bot): 😱 plant tree 🌳"
          arr[2]="chore(bot): 👿 plant tree 🌳"
          arr[3]="chore(bot): 💩 plant tree 🌳"
          arr[4]="chore(bot): 🙏 plant tree 🌳"
          arr[5]="chore(bot): 🙈 plant tree 🌳"
          arr[6]="chore(bot): 🐐 plant tree 🌳"
          arr[7]="chore(bot): 🤖 plant tree 🌳"
          arr[8]="chore(bot): 😛 plant tree 🌳"
          arr[9]="chore(bot): 👻 plant tree 🌳"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
